# Generated by Django 6.0.3 on 2026-03-10 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_remove_department_created_at_and_more'),
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='duplicate_of',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='internal_note',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='submission_type',
        ),
        migrations.RemoveField(
            model_name='ticketcomment',
            name='user',
        ),
        migrations.AddField(
            model_name='ticketcomment',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.department'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='TicketActivityLog',
        ),
    ]
